  language: python
  python:
  
      - "3.6" 
  
  # command to install dependencies

  install:
  - pip3 install -r ./requirements.txt
  - pip3 install coveralls
  - pip3 install coverage
  - pip3 install pytest pytest-cov
  
  
  script:
  - pytest --cov= ./api/v2/    #api/v2/test_app.py #--doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
  
# push report to coveralls.io
after_success:
- coveralls

