  language: python
  python:
  
      - "3.6" 
  
  # command to install dependencies

  install:
  - pip3 install -r ./requirements.txt
  - pip3 install coveralls
  
  script:
  - python manage.py run_test
  - coverage run --source='.' --omit='/api/v2/*'  test_app.py run_test
  - coverage report --omit='./*'

# push report to coveralls.io
after_success:
- coveralls

