language: python
python:  
  - "3.6" 

install:
  - pip install -r ./requirements.txt
  - pip install coverage
  - pip install coveralls
  
script:
  - coverage run --source= ./api/v2/test_app.py 
  - coverage report --omit='./*'

after_success:
  - coveralls

